[package]
name = "ort_common"
version = "0.1.0"
edition = "2024"

[dependencies]
# internal
inference_common.workspace = true
# external
anyhow.workspace = true
log.workspace = true
ndarray.workspace = true
ort.workspace = true
