#!/bin/bash
# Test Zone Movement Feature
# This script validates the Alt+Arrows movement controls

echo "Zone Movement Feature Test"
echo "==========================="
echo ""
echo "Build completed successfully!"
echo ""
echo "Manual Test Instructions:"
echo "1. Run: ./target/release/gstreamed_ort webcam_test.mp4"
echo "2. Press 'r' to enter ROI mode"
echo "3. Press 'n' to create a new zone"
echo "4. Test the controls:"
echo ""
echo "   RESIZE Bottom-Right (default):"
echo "   - Arrow keys: Move bottom-right corner"
echo "   - Shift+Arrows: Fine adjustment (0.01)"
echo ""
echo "   RESIZE Top-Left:"
echo "   - Ctrl+Arrows: Move top-left corner"
echo "   - Ctrl+Shift+Arrows: Fine adjustment"
echo ""
echo "   MOVE Zone (NEW!):"
echo "   - Alt+Arrows: Move entire zone"
echo "   - Alt+Shift+Arrows: Fine movement (0.01)"
echo ""
echo "5. Test boundary conditions:"
echo "   - Move zone to right edge (xmax=1.0)"
echo "   - Try Alt+Right: should NOT move beyond boundary"
echo "   - Move zone to left edge (xmin=0.0)"
echo "   - Try Alt+Left: should NOT move beyond boundary"
echo ""
echo "6. Press 's' to save zone"
echo "7. Press Esc to exit zone editor"
echo ""
echo "Expected Results:"
echo "✅ Alt+Arrows moves entire zone without changing size"
echo "✅ Movement stops at boundaries [0.0, 1.0]"
echo "✅ Ctrl+Arrows still resize top-left corner"
echo "✅ Plain Arrows still resize bottom-right corner"
echo "✅ Shift modifier works with all modes for fine control"
echo ""
